import { Container } from '../components/shared/Container'

export default function Terms() {
  return (
    <section className="pt-28 pb-24">
      <Container width="3xl" padding="default">
        <p className="text-xs font-mono tracking-widest uppercase text-primary-accessible mb-4">Legal</p>
        <h1 className="text-3xl font-semibold text-ink mb-2">Terms &amp; Conditions</h1>
        <p className="text-ink-tertiary font-mono text-xs mb-10">Updated at 2026-05-16</p>

        <div className="space-y-10 text-sm text-ink-secondary leading-relaxed">

          <section>
            <h2 className="text-ink text-base font-semibold mb-3">General Terms</h2>
            <p className="mb-3">
              By accessing or using the DeployTitan service, you confirm that you are in agreement
              with and bound by the terms of service contained in the Terms &amp; Conditions outlined
              below. These terms apply to the entire website, the platform, and any email or other
              type of communication between you and DeployTitan.
            </p>
            <p className="mb-3">
              Under no circumstances shall DeployTitan team be liable for any direct, indirect,
              special, incidental or consequential damages, including, but not limited to, loss of
              data or profit, arising out of the use, or the inability to use, the materials on this
              site, even if DeployTitan team or an authorized representative has been advised of the
              possibility of such damages. If your use of materials from this site results in the
              need for servicing, repair or correction of equipment or data, you assume any costs
              thereof.
            </p>
            <p>
              DeployTitan will not be responsible for any outcome that may occur during the course
              of usage of our resources. We reserve the rights to change prices and revise the
              resources usage policy in any moment.
            </p>
          </section>

          <section>
            <h2 className="text-ink text-base font-semibold mb-3">License</h2>
            <p className="mb-3">
              DeployTitan grants you a revocable, non-exclusive, non-transferable, limited license
              to download, install and use the website strictly in accordance with the terms of this
              Agreement.
            </p>
            <p className="mb-3">
              These Terms &amp; Conditions are a contract between you and DeployTitan (referred to
              in these Terms &amp; Conditions as &quot;DeployTitan&quot;, &quot;us&quot;,
              &quot;we&quot; or &quot;our&quot;), the provider of the DeployTitan website and the
              services accessible from the DeployTitan website (which are collectively referred to
              in these Terms &amp; Conditions as the &quot;DeployTitan Service&quot;).
            </p>
            <p>
              You are agreeing to be bound by these Terms &amp; Conditions. If you do not agree to
              these Terms &amp; Conditions, please do not use the DeployTitan Service. In these
              Terms &amp; Conditions, &quot;you&quot; refers both to you as an individual and to the
              entity you represent. If you violate any of these Terms &amp; Conditions, we reserve
              the right to cancel your account or block access to your account without notice.
            </p>
          </section>

          <section>
            <h2 className="text-ink text-base font-semibold mb-3">Definitions and Key Terms</h2>
            <p className="mb-3">
              To help explain things as clearly as possible in this Terms &amp; Conditions, every
              time any of these terms are referenced, are strictly defined as:
            </p>
            <ul className="space-y-2 list-none">
              <li><span className="text-ink font-medium">Cookie:</span> small amount of data generated by a website and saved by your web browser. It is used to identify your browser, provide analytics, remember information about you such as your language preference or login information.</li>
              <li><span className="text-ink font-medium">Company:</span> when this policy mentions &quot;Company,&quot; &quot;we,&quot; &quot;us,&quot; or &quot;our,&quot; it refers to DeployTitan, that is responsible for your information under this Terms &amp; Conditions.</li>
              <li><span className="text-ink font-medium">Device:</span> any internet connected device such as a phone, tablet, computer or any other device that can be used to visit DeployTitan and use the services.</li>
              <li><span className="text-ink font-medium">Service:</span> refers to the service provided by DeployTitan as described in the relative terms (if available) and on this platform.</li>
              <li><span className="text-ink font-medium">Third-party service:</span> refers to analytics providers, infrastructure vendors, billing processors, and other service providers whose tools or services we use to operate and improve the DeployTitan platform.</li>
              <li><span className="text-ink font-medium">Website:</span> DeployTitan&apos;s site, which can be accessed via this URL: https://deploytitan.com</li>
              <li><span className="text-ink font-medium">You:</span> a person or entity that is registered with DeployTitan to use the Services.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-ink text-base font-semibold mb-3">Restrictions</h2>
            <p className="mb-3">You agree not to, and you will not permit others to:</p>
            <ul className="space-y-2 list-none">
              <li>License, sell, rent, lease, assign, distribute, transmit, host, outsource, disclose or otherwise commercially exploit the website or make the platform available to any third party.</li>
              <li>Modify, make derivative works of, disassemble, decrypt, reverse compile or reverse engineer any part of the website.</li>
              <li>Remove, alter or obscure any proprietary notice (including any notice of copyright or trademark) of DeployTitan or its affiliates, partners, suppliers or the licensors of the website.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-ink text-base font-semibold mb-3">Subscription and Refund Policy</h2>
            <p className="mb-3">
              DeployTitan is a subscription-based SaaS platform. Subscriptions are billed on a
              monthly or annual basis depending on the plan you select at signup.
            </p>
            <p className="mb-3">
              If you are not satisfied with the service, please contact us within 14 days of your
              initial subscription or renewal and we will work with you to resolve the issue. Refund
              eligibility is assessed on a case-by-case basis at DeployTitan&apos;s discretion.
            </p>
            <p>
              You may cancel your subscription at any time from your account settings. Cancellation
              takes effect at the end of the current billing period. No partial refunds are issued
              for unused time in a billing period unless required by applicable law.
            </p>
          </section>

          <section>
            <h2 className="text-ink text-base font-semibold mb-3">Your Suggestions</h2>
            <p className="mb-3">
              Any feedback, comments, ideas, improvements or suggestions (collectively,
              &quot;Suggestions&quot;) provided by you to DeployTitan with respect to the website
              shall remain the sole and exclusive property of DeployTitan.
            </p>
            <p>
              DeployTitan shall be free to use, copy, modify, publish, or redistribute the
              Suggestions for any purpose and in any way without any credit or any compensation to
              you.
            </p>
          </section>

          <section>
            <h2 className="text-ink text-base font-semibold mb-3">Your Consent</h2>
            <p>
              We&apos;ve updated our Terms &amp; Conditions to provide you with complete
              transparency into what is being set when you visit our site and how it&apos;s being
              used.               By using our website, registering an account, or subscribing to our service, you hereby
              consent to our Terms &amp; Conditions.
            </p>
          </section>

          <section>
            <h2 className="text-ink text-base font-semibold mb-3">Links to Other Websites</h2>
            <p>
              This Terms &amp; Conditions applies only to the Services. The Services may contain
              links to other websites not operated or controlled by DeployTitan. We are not
              responsible for the content, accuracy or opinions expressed in such websites, and such
              websites are not investigated, monitored or checked for accuracy or completeness by
              us. Please remember that when you use a link to go from the Services to another
              website, our Terms &amp; Conditions are no longer in effect. Your browsing and
              interaction on any other website, including those that have a link on our platform, is
              subject to that website&apos;s own rules and policies. Such third parties may use
              their own cookies or other methods to collect information about you.
            </p>
          </section>

          <section>
            <h2 className="text-ink text-base font-semibold mb-3">Cookies</h2>
            <p>
              DeployTitan uses &quot;Cookies&quot; to identify the areas of our website that you
              have visited. A Cookie is a small piece of data stored on your computer or mobile
              device by your web browser. We use Cookies to enhance the performance and
              functionality of our website but are non-essential to their use. However, without
              these cookies, certain functionality like videos may become unavailable or you would
              be required to enter your login details every time you visit the website as we would
              not be able to remember that you had logged in previously. Most web browsers can be
              set to disable the use of Cookies. However, if you disable Cookies, you may not be
              able to access functionality on our website correctly or at all. We never place
              Personally Identifiable Information in Cookies.
            </p>
          </section>

          <section>
            <h2 className="text-ink text-base font-semibold mb-3">Changes to Our Terms &amp; Conditions</h2>
            <p className="mb-3">
              You acknowledge and agree that DeployTitan may stop (permanently or temporarily)
              providing the Service (or any features within the Service) to you or to users
              generally at sole discretion, without prior notice to you. You may stop using the
              Service at any time. You do not need to specifically inform DeployTitan when you stop
              using the Service. You acknowledge and agree that if DeployTitan disables access to
              your account, you may be prevented from accessing the Service, your account details or
              any files or other materials which is contained in your account.
            </p>
            <p>
              If we decide to change our Terms &amp; Conditions, we will post those changes on this
              page, and/or update the Terms &amp; Conditions modification date below.
            </p>
          </section>

          <section>
            <h2 className="text-ink text-base font-semibold mb-3">Modifications to Our Website</h2>
            <p>
              DeployTitan reserves the right to modify, suspend or discontinue, temporarily or
              permanently, the website or any service to which it connects, with or without notice
              and without liability to you.
            </p>
          </section>

          <section>
            <h2 className="text-ink text-base font-semibold mb-3">Updates to Our Website</h2>
            <p className="mb-3">
              DeployTitan may from time to time provide enhancements or improvements to the
              features/functionality of the website, which may include patches, bug fixes, updates,
              upgrades and other modifications (&quot;Updates&quot;).
            </p>
            <p className="mb-3">
              Updates may modify or delete certain features and/or functionalities of the website.
              You agree that DeployTitan has no obligation to (i) provide any Updates, or (ii)
              continue to provide or enable any particular features and/or functionalities of the
              website to you.
            </p>
            <p>
              You further agree that all Updates will be (i) deemed to constitute an integral part
              of the website, and (ii) subject to the terms and conditions of this Agreement.
            </p>
          </section>

          <section>
            <h2 className="text-ink text-base font-semibold mb-3">Third-Party Services</h2>
            <p className="mb-3">
              We may display, include or make available third-party content (including data,
              information, applications and other products services) or provide links to third-party
              websites or services (&quot;Third-Party Services&quot;).
            </p>
            <p className="mb-3">
              You acknowledge and agree that DeployTitan shall not be responsible for any
              Third-Party Services, including their accuracy, completeness, timeliness, validity,
              copyright compliance, legality, decency, quality or any other aspect thereof.
              DeployTitan does not assume and shall not have any liability or responsibility to you
              or any other person or entity for any Third-Party Services.
            </p>
            <p>
              Third-Party Services and links thereto are provided solely as a convenience to you and
              you access and use them entirely at your own risk and subject to such third
              parties&apos; terms and conditions.
            </p>
          </section>

          <section>
            <h2 className="text-ink text-base font-semibold mb-3">Term and Termination</h2>
            <p className="mb-3">
              This Agreement shall remain in effect until terminated by you or DeployTitan.
            </p>
            <p className="mb-3">
              DeployTitan may, in its sole discretion, at any time and for any or no reason,
              suspend or terminate this Agreement with or without prior notice.
            </p>
            <p className="mb-3">
              This Agreement will terminate immediately, without prior notice from DeployTitan, in
              the event that you fail to comply with any provision of this Agreement. You may also
              terminate this Agreement by cancelling your account and ceasing all use of the
              DeployTitan service.
            </p>
            <p className="mb-3">
              Upon termination of this Agreement, you shall cease all use of the service and your
              access to the platform will be revoked.</p>
            <p>
              Termination of this Agreement will not limit any of DeployTitan&apos;s rights or
              remedies at law or in equity in case of breach by you (during the term of this
              Agreement) of any of your obligations under the present Agreement.
            </p>
          </section>

          <section>
            <h2 className="text-ink text-base font-semibold mb-3">Copyright Infringement Notice</h2>
            <p>
              If you are a copyright owner or such owner&apos;s agent and believe any material on
              our website constitutes an infringement on your copyright, please contact us setting
              forth the following information: (a) a physical or electronic signature of the
              copyright owner or a person authorized to act on his behalf; (b) identification of the
              material that is claimed to be infringing; (c) your contact information, including
              your address, telephone number, and an email; (d) a statement by you that you have a
              good faith belief that use of the material is not authorized by the copyright owners;
              and (e) a statement that the information in the notification is accurate, and, under
              penalty of perjury you are authorized to act on behalf of the owner.
            </p>
          </section>

          <section>
            <h2 className="text-ink text-base font-semibold mb-3">Indemnification</h2>
            <p>
              You agree to indemnify and hold DeployTitan and its parents, subsidiaries, affiliates,
              officers, employees, agents, partners and licensors (if any) harmless from any claim
              or demand, including reasonable attorneys&apos; fees, due to or arising out of your:
              (a) use of the website; (b) violation of this Agreement or any law or regulation; or
              (c) violation of any right of a third party.
            </p>
          </section>

          <section>
            <h2 className="text-ink text-base font-semibold mb-3">No Warranties</h2>
            <p className="mb-3">
              The website is provided to you &quot;AS IS&quot; and &quot;AS AVAILABLE&quot; and with
              all faults and defects without warranty of any kind. To the maximum extent permitted
              under applicable law, DeployTitan, on its own behalf and on behalf of its affiliates
              and its and their respective licensors and service providers, expressly disclaims all
              warranties, whether express, implied, statutory or otherwise, with respect to the
              website, including all implied warranties of merchantability, fitness for a particular
              purpose, title and non-infringement, and warranties that may arise out of course of
              dealing, course of performance, usage or trade practice.
            </p>
            <p>
              Without limiting the foregoing, neither DeployTitan nor any DeployTitan&apos;s
              provider makes any representation or warranty of any kind, express or implied: (i) as
              to the operation or availability of the website, or the information, content, and
              materials or products included thereon; (ii) that the website will be uninterrupted or
              error-free; (iii) as to the accuracy, reliability, or currency of any information or
              content provided through the website; or (iv) that the website, its servers, the
              content, or e-mails sent from or on behalf of DeployTitan are free of viruses, scripts,
              trojan horses, worms, malware, timebombs or other harmful components.
            </p>
          </section>

          <section>
            <h2 className="text-ink text-base font-semibold mb-3">Limitation of Liability</h2>
            <p className="mb-3">
              Notwithstanding any damages that you might incur, the entire liability of DeployTitan
              and any of its suppliers under any provision of this Agreement and your exclusive
              remedy for all of the foregoing shall be limited to the amount actually paid by you
              for the DeployTitan subscription in the twelve (12) months preceding the claim.
            </p>
            <p>
              To the maximum extent permitted by applicable law, in no event shall DeployTitan or
              its suppliers be liable for any special, incidental, indirect, or consequential damages
              whatsoever (including, but not limited to, damages for loss of profits, for loss of
              data or other information, for business interruption, for personal injury, for loss of
              privacy arising out of or in any way related to the use of or inability to use the
              website, third-party software and/or third-party hardware used with the website, or
              otherwise in connection with any provision of this Agreement), even if DeployTitan or
              any supplier has been advised of the possibility of such damages and even if the
              remedy fails of its essential purpose.
            </p>
          </section>

          <section>
            <h2 className="text-ink text-base font-semibold mb-3">Severability</h2>
            <p>
              If any provision of this Agreement is held to be unenforceable or invalid, such
              provision will be changed and interpreted to accomplish the objectives of such
              provision to the greatest extent possible under applicable law and the remaining
              provisions will continue in full force and effect. This Agreement, together with the
              Privacy Policy and any other legal notices published by DeployTitan on the Services,
              shall constitute the entire agreement between you and DeployTitan concerning the
              Services.
            </p>
          </section>

          <section>
            <h2 className="text-ink text-base font-semibold mb-3">Waiver</h2>
            <p>
              Except as provided herein, the failure to exercise a right or to require performance
              of an obligation under this Agreement shall not effect a party&apos;s ability to
              exercise such right or require such performance at any time thereafter nor shall the
              waiver of a breach constitute waiver of any subsequent breach.
            </p>
          </section>

          <section>
            <h2 className="text-ink text-base font-semibold mb-3">Amendments to this Agreement</h2>
            <p className="mb-3">
              DeployTitan reserves the right, at its sole discretion, to modify or replace this
              Agreement at any time. If a revision is material we will provide at least 30
              days&apos; notice prior to any new terms taking effect. What constitutes a material
              change will be determined at our sole discretion.
            </p>
            <p>
              By continuing to access or use our website after any revisions become effective, you
              agree to be bound by the revised terms. If you do not agree to the new terms, you are
              no longer authorized to use DeployTitan.
            </p>
          </section>

          <section>
            <h2 className="text-ink text-base font-semibold mb-3">Entire Agreement</h2>
            <p className="mb-3">
              The Agreement constitutes the entire agreement between you and DeployTitan regarding
              your use of the website and supersedes all prior and contemporaneous written or oral
              agreements between you and DeployTitan.
            </p>
            <p>
              You may be subject to additional terms and conditions that apply when you use or
              purchase other DeployTitan services, which DeployTitan will provide to you at the time
              of such use or purchase.
            </p>
          </section>

          <section>
            <h2 className="text-ink text-base font-semibold mb-3">Intellectual Property</h2>
            <p>
              The website and its entire contents, features and functionality (including but not
              limited to all information, software, text, displays, images, video and audio, and the
              design, selection and arrangement thereof), are owned by DeployTitan, its licensors or
              other providers of such material and are protected by international copyright,
              trademark, patent, trade secret and other intellectual property or proprietary rights
              laws. The material may not be copied, modified, reproduced, downloaded or distributed
              in any way, in whole or in part, without the express prior written permission of
              DeployTitan, unless and except as is expressly provided in these Terms &amp;
              Conditions. Any unauthorized use of the material is prohibited.
            </p>
          </section>

          <section>
            <h2 className="text-ink text-base font-semibold mb-3">Agreement to Arbitrate</h2>
            <p>
              This section applies to any dispute except it does not include a dispute relating to
              claims for injunctive or equitable relief regarding the enforcement or validity of
              your or DeployTitan&apos;s intellectual property rights. The term
              &quot;dispute&quot; means any dispute, action, or other controversy between you and
              DeployTitan concerning the Services or this agreement, whether in contract, warranty,
              tort, statute, regulation, ordinance, or any other legal or equitable basis.
            </p>
          </section>

          <section>
            <h2 className="text-ink text-base font-semibold mb-3">Notice of Dispute</h2>
            <p>
              In the event of a dispute, you or DeployTitan must give the other a Notice of Dispute,
              which is a written statement that sets forth the name, address, and contact
              information of the party giving it, the facts giving rise to the dispute, and the
              relief requested. You and DeployTitan will attempt to resolve any dispute through
              informal negotiation within sixty (60) days from the date the Notice of Dispute is
              sent. After sixty (60) days, you or DeployTitan may commence arbitration.
            </p>
          </section>

          <section>
            <h2 className="text-ink text-base font-semibold mb-3">Binding Arbitration</h2>
            <p>
              If you and DeployTitan don&apos;t resolve any dispute by informal negotiation, any
              other effort to resolve the dispute will be conducted exclusively by binding
              arbitration as described in this section. You are giving up the right to litigate (or
              participate in as a party or class member) all disputes in court before a judge or
              jury. The dispute shall be settled by binding arbitration in accordance with the
              commercial arbitration rules of the American Arbitration Association. Either party may
              seek any interim or preliminary injunctive relief from any court of competent
              jurisdiction, as necessary to protect the party&apos;s rights or property pending the
              completion of arbitration. Any and all legal, accounting, and other costs, fees, and
              expenses incurred by the prevailing party shall be borne by the non-prevailing party.
            </p>
          </section>

          <section>
            <h2 className="text-ink text-base font-semibold mb-3">Submissions and Privacy</h2>
            <p>
              In the event that you submit or post any ideas, creative suggestions, designs,
              information, data or proposals, including ideas for new or improved products, services,
              or features, you expressly agree that such submissions will automatically be treated as
              non-confidential and non-proprietary and will become the sole property of DeployTitan
              without any compensation or credit to you whatsoever. DeployTitan and its affiliates
              shall have no obligations with respect to such submissions or posts and may use the
              ideas contained in such submissions or posts for any purposes in any medium in
              perpetuity, including, but not limited to, developing and improving the DeployTitan
              service using such ideas.
            </p>
          </section>

          <section>
            <h2 className="text-ink text-base font-semibold mb-3">Typographical Errors</h2>
            <p>
              In the event a plan or service is listed at an incorrect price or with incorrect
              information due to a typographical error, we reserve the right to correct the error and
              bill at the correct price going forward, or to cancel and refund any affected
              subscriptions initiated at the incorrect price. We will notify affected subscribers
              before any such correction takes effect.
            </p>
          </section>

          <section>
            <h2 className="text-ink text-base font-semibold mb-3">Disclaimer</h2>
            <p className="mb-3">
              DeployTitan is not responsible for any content, code or any other imprecision.
              DeployTitan does not provide warranties or guarantees.
            </p>
            <p>
              In no event shall DeployTitan be liable for any special, direct, indirect,
              consequential, or incidental damages or any damages whatsoever, whether in an action
              of contract, negligence or other tort, arising out of or in connection with the use of
              the Service or the contents of the Service. The Company reserves the right to make
              additions, deletions, or modifications to the contents on the Service at any time
              without prior notice.
            </p>
          </section>

          <section>
            <h2 className="text-ink text-base font-semibold mb-3">Contact Us</h2>
            <p>
              Don&apos;t hesitate to contact us if you have any questions.
            </p>
            <ul className="mt-2 list-none">
              <li>
                Via Email:{' '}
                <a href="mailto:legal@deploytitan.com" className="text-primary-accessible hover:underline">
                  legal@deploytitan.com
                </a>
              </li>
            </ul>
          </section>

        </div>
      </Container>
    </section>
  )
}
