/**
 * scripts/build-link-graph.ts
 *
 * Prebuild script that scans all app/ page files and src/page-components/ for
 * Next.js <Link href="..."> and plain <a href="..."> tags, then writes
 * src/data/siteGraph.generated.ts with the discovered nodes and links.
 *
 * Run via:  tsx scripts/build-link-graph.ts
 * Wired as: "prebuild" in package.json
 */

import { readdirSync, readFileSync, writeFileSync, statSync } from 'fs'
import { join, relative, dirname } from 'path'
import { fileURLToPath } from 'url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const ROOT = join(__dirname, '..')
const APP_DIR = join(ROOT, 'src/app')
const PAGES_DIR = join(ROOT, 'src/page-components')
const OUT_FILE = join(ROOT, 'src/data/siteGraph.generated.ts')

// ── Route discovery ──────────────────────────────────────────────────────────

function appDirToRoute(filePath: string): string {
  const rel = relative(APP_DIR, filePath)
    .replace(/\/page\.tsx$/, '')
    .replace(/^page\.tsx$/, '')
  const route = '/' + rel.replace(/\[([^\]]+)\]/g, ':$1')
  return route === '//' ? '/' : route || '/'
}

function walk(dir: string, ext: string[]): string[] {
  const results: string[] = []
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry)
    if (statSync(full).isDirectory()) {
      results.push(...walk(full, ext))
    } else if (ext.some((e) => full.endsWith(e))) {
      results.push(full)
    }
  }
  return results
}

// ── Link extraction ──────────────────────────────────────────────────────────

const LINK_RE = /(?:href|to)=["'`](\/?[a-z0-9][a-z0-9/_-]*)["'`]/gi
const DYNAMIC_LINK_RE = /(?:href|to)=\{[^}]*["'`](\/[a-z0-9][a-z0-9/_-]*)["'`]/gi

function extractLinks(source: string): string[] {
  const links: string[] = []
  let m: RegExpExecArray | null
  LINK_RE.lastIndex = 0
  while ((m = LINK_RE.exec(source)) !== null) {
    const href = m[1]
    if (href.startsWith('/') && !href.startsWith('//')) links.push(href)
  }
  DYNAMIC_LINK_RE.lastIndex = 0
  while ((m = DYNAMIC_LINK_RE.exec(source)) !== null) {
    const href = m[1]
    if (href.startsWith('/') && !href.startsWith('//')) links.push(href)
  }
  return [...new Set(links)]
}

// ── Build graph ──────────────────────────────────────────────────────────────

function slugToLabel(route: string): string {
  const last = route.split('/').filter(Boolean).pop() ?? ''
  return last
    .replace(/-/g, ' ')
    .replace(/\b\w/g, (c) => c.toUpperCase()) || 'Home'
}

const nodes = new Map<string, { id: string; label: string; file: string }>()
const links: { source: string; target: string; kind: 'nav' | 'link' | 'href' }[] = []

// Register all app routes as nodes
const appPageFiles = walk(APP_DIR, ['.tsx'])
  .filter((f) => f.endsWith('/page.tsx') || f.endsWith('\\page.tsx'))

for (const file of appPageFiles) {
  const route = appDirToRoute(file)
  if (route.includes(':')) continue // skip dynamic routes as nodes
  nodes.set(route, {
    id: route,
    label: slugToLabel(route),
    file: relative(ROOT, file),
  })
}

// Extract links from page-components
const componentFiles = walk(PAGES_DIR, ['.tsx', '.ts'])

for (const file of componentFiles) {
  const source = readFileSync(file, 'utf8')
  const hrefs = extractLinks(source)
  // Determine source route from filename
  const relFile = relative(PAGES_DIR, file)
    .replace(/\.tsx?$/, '')
    .replace(/\\/g, '/')
  const sourceRoute = '/' + relFile
    .replace(/\/index$/, '')
    .replace(/([A-Z])/g, (c) => '-' + c.toLowerCase())
    .replace(/^-/, '')

  for (const href of hrefs) {
    if (nodes.has(href)) {
      links.push({ source: sourceRoute, target: href, kind: 'link' })
    }
  }
}

// Also scan nav components for nav-level links
const navFiles = walk(join(ROOT, 'src/components/nav'), ['.tsx'])
for (const file of navFiles) {
  const source = readFileSync(file, 'utf8')
  const hrefs = extractLinks(source)
  for (const href of hrefs) {
    if (nodes.has(href)) {
      links.push({ source: '__nav__', target: href, kind: 'nav' })
    }
  }
}

// ── Write output ─────────────────────────────────────────────────────────────

const nodesArr = [...nodes.values()]

const out = `// AUTO-GENERATED by scripts/build-link-graph.ts — do not edit manually
// Re-generated on every build via "prebuild" script

export interface GraphNode {
  id: string
  label: string
  file: string
}

export interface GraphLink {
  source: string
  target: string
  kind: 'nav' | 'link' | 'href'
}

export const generatedNodes: GraphNode[] = ${JSON.stringify(nodesArr, null, 2)}

export const generatedLinks: GraphLink[] = ${JSON.stringify(links, null, 2)}
`

writeFileSync(OUT_FILE, out, 'utf8')
console.log(`[build-link-graph] wrote ${nodesArr.length} nodes, ${links.length} links → ${relative(ROOT, OUT_FILE)}`)
