// AUTO-GENERATED by vite-plugin-link-graph — do not edit manually
// Re-generated on every dev-server start and build

export interface GraphNode {
  id: string
  label: string
  file: string
}

export interface GraphLink {
  source: string
  target: string
  kind: 'nav' | 'link' | 'href'
}

export const generatedNodes: GraphNode[] = [
  {
    "id": "/solutions",
    "label": "Solutions",
    "file": "App.tsx"
  },
  {
    "id": "/solutions/progressive-delivery",
    "label": "Solutions › Progressive Delivery",
    "file": "App.tsx"
  },
  {
    "id": "/solutions/multi-cloud-resilience",
    "label": "Solutions › Multi Cloud Resilience",
    "file": "App.tsx"
  },
  {
    "id": "/solutions/risk-intelligence",
    "label": "Solutions › Risk Intelligence",
    "file": "App.tsx"
  },
  {
    "id": "/solutions/platform-engineering",
    "label": "Solutions › Platform Engineering",
    "file": "App.tsx"
  },
  {
    "id": "/pricing",
    "label": "Pricing",
    "file": "App.tsx"
  },
  {
    "id": "/customers",
    "label": "Customers",
    "file": "App.tsx"
  },
  {
    "id": "/blog",
    "label": "Blog",
    "file": "App.tsx"
  },
  {
    "id": "/changelog",
    "label": "Changelog",
    "file": "App.tsx"
  },
  {
    "id": "/docs",
    "label": "Docs",
    "file": "App.tsx"
  },
  {
    "id": "/about",
    "label": "About",
    "file": "App.tsx"
  },
  {
    "id": "/journey",
    "label": "Journey",
    "file": "App.tsx"
  },
  {
    "id": "/how-it-works",
    "label": "How It Works",
    "file": "App.tsx"
  },
  {
    "id": "/security",
    "label": "Security",
    "file": "App.tsx"
  },
  {
    "id": "/early-access",
    "label": "Early Access",
    "file": "App.tsx"
  },
  {
    "id": "/for/sre",
    "label": "For › Sre",
    "file": "App.tsx"
  },
  {
    "id": "/for/devops",
    "label": "For › Devops",
    "file": "App.tsx"
  },
  {
    "id": "/for/cto",
    "label": "For › Cto",
    "file": "App.tsx"
  },
  {
    "id": "/products/titan-rollout",
    "label": "Products › Titan Rollout",
    "file": "App.tsx"
  },
  {
    "id": "/products/titan-shield",
    "label": "Products › Titan Shield",
    "file": "App.tsx"
  },
  {
    "id": "/products/titan-sentinel",
    "label": "Products › Titan Sentinel",
    "file": "App.tsx"
  },
  {
    "id": "/products/titan-pulse",
    "label": "Products › Titan Pulse",
    "file": "App.tsx"
  },
  {
    "id": "/terms",
    "label": "Terms",
    "file": "App.tsx"
  },
  {
    "id": "/privacy",
    "label": "Privacy",
    "file": "App.tsx"
  },
  {
    "id": "/status",
    "label": "Status",
    "file": "App.tsx"
  },
  {
    "id": "/cli",
    "label": "Cli",
    "file": "App.tsx"
  },
  {
    "id": "/api",
    "label": "Api",
    "file": "App.tsx"
  },
  {
    "id": "/roadmap",
    "label": "Roadmap",
    "file": "App.tsx"
  },
  {
    "id": "/careers",
    "label": "Careers",
    "file": "App.tsx"
  },
  {
    "id": "/contact",
    "label": "Contact",
    "file": "App.tsx"
  },
  {
    "id": "/press",
    "label": "Press",
    "file": "App.tsx"
  },
  {
    "id": "/brand",
    "label": "Brand",
    "file": "App.tsx"
  },
  {
    "id": "/partners",
    "label": "Partners",
    "file": "App.tsx"
  },
  {
    "id": "/sitemap",
    "label": "Sitemap",
    "file": "App.tsx"
  },
  {
    "id": "/integrations",
    "label": "Integrations",
    "file": "App.tsx"
  },
  {
    "id": "/integrations/:slug",
    "label": "Integrations › :Slug",
    "file": "App.tsx"
  }
]

export const generatedLinks: GraphLink[] = [
  {
    "source": "/roadmap",
    "target": "/changelog",
    "kind": "link"
  },
  {
    "source": "/integrations",
    "target": "/api",
    "kind": "link"
  },
  {
    "source": "/how-it-works",
    "target": "/docs",
    "kind": "link"
  },
  {
    "source": "/how-it-works",
    "target": "/security",
    "kind": "link"
  },
  {
    "source": "/early-access",
    "target": "/docs",
    "kind": "link"
  },
  {
    "source": "/early-access",
    "target": "/products/titan-rollout",
    "kind": "link"
  },
  {
    "source": "/docs",
    "target": "/cli",
    "kind": "link"
  },
  {
    "source": "/cli",
    "target": "/api",
    "kind": "link"
  },
  {
    "source": "/cli",
    "target": "/integrations",
    "kind": "link"
  },
  {
    "source": "/about",
    "target": "/careers",
    "kind": "link"
  },
  {
    "source": "/api",
    "target": "/cli",
    "kind": "link"
  },
  {
    "source": "/products/titan-shield",
    "target": "/solutions",
    "kind": "link"
  },
  {
    "source": "/products/titan-sentinel",
    "target": "/solutions",
    "kind": "link"
  },
  {
    "source": "/products/titan-rollout",
    "target": "/solutions",
    "kind": "link"
  },
  {
    "source": "/products/titan-pulse",
    "target": "/early-access",
    "kind": "link"
  },
  {
    "source": "/products/titan-pulse",
    "target": "/how-it-works",
    "kind": "link"
  },
  {
    "source": "/solutions/risk-intelligence",
    "target": "/solutions",
    "kind": "link"
  },
  {
    "source": "/solutions/risk-intelligence",
    "target": "/products/titan-sentinel",
    "kind": "link"
  },
  {
    "source": "/solutions/progressive-delivery",
    "target": "/solutions",
    "kind": "link"
  },
  {
    "source": "/solutions/progressive-delivery",
    "target": "/products/titan-rollout",
    "kind": "link"
  },
  {
    "source": "/solutions/platform-engineering",
    "target": "/solutions",
    "kind": "link"
  },
  {
    "source": "/solutions/multi-cloud-resilience",
    "target": "/solutions",
    "kind": "link"
  },
  {
    "source": "/solutions/multi-cloud-resilience",
    "target": "/products/titan-shield",
    "kind": "link"
  }
]
