// AUTO-GENERATED by scripts/build-link-graph.ts — do not edit manually
// Re-generated on every build via "prebuild" script

export interface GraphNode {
  id: string
  label: string
  file: string
}

export interface GraphLink {
  source: string
  target: string
  kind: 'nav' | 'link' | 'href'
}

export const generatedNodes: GraphNode[] = [
  {
    "id": "/about",
    "label": "About",
    "file": "src/app/about/page.tsx"
  },
  {
    "id": "/api-reference",
    "label": "Api Reference",
    "file": "src/app/api-reference/page.tsx"
  },
  {
    "id": "/blog",
    "label": "Blog",
    "file": "src/app/blog/page.tsx"
  },
  {
    "id": "/cli",
    "label": "Cli",
    "file": "src/app/cli/page.tsx"
  },
  {
    "id": "/contact",
    "label": "Contact",
    "file": "src/app/contact/page.tsx"
  },
  {
    "id": "/docs",
    "label": "Docs",
    "file": "src/app/docs/page.tsx"
  },
  {
    "id": "/for/cto",
    "label": "Cto",
    "file": "src/app/for/cto/page.tsx"
  },
  {
    "id": "/for/devops",
    "label": "Devops",
    "file": "src/app/for/devops/page.tsx"
  },
  {
    "id": "/for/sre",
    "label": "Sre",
    "file": "src/app/for/sre/page.tsx"
  },
  {
    "id": "/how-it-works",
    "label": "How It Works",
    "file": "src/app/how-it-works/page.tsx"
  },
  {
    "id": "/journey",
    "label": "Journey",
    "file": "src/app/journey/page.tsx"
  },
  {
    "id": "/",
    "label": "Home",
    "file": "src/app/page.tsx"
  },
  {
    "id": "/pricing",
    "label": "Pricing",
    "file": "src/app/pricing/page.tsx"
  },
  {
    "id": "/privacy",
    "label": "Privacy",
    "file": "src/app/privacy/page.tsx"
  },
  {
    "id": "/products/titan-foresight",
    "label": "Titan Foresight",
    "file": "src/app/products/titan-foresight/page.tsx"
  },
  {
    "id": "/products/titan-phoenix",
    "label": "Titan Phoenix",
    "file": "src/app/products/titan-phoenix/page.tsx"
  },
  {
    "id": "/products/titan-rollout",
    "label": "Titan Rollout",
    "file": "src/app/products/titan-rollout/page.tsx"
  },
  {
    "id": "/security",
    "label": "Security",
    "file": "src/app/security/page.tsx"
  },
  {
    "id": "/sitemap",
    "label": "Sitemap",
    "file": "src/app/sitemap/page.tsx"
  },
  {
    "id": "/solutions/instant-rollback",
    "label": "Instant Rollback",
    "file": "src/app/solutions/instant-rollback/page.tsx"
  },
  {
    "id": "/solutions",
    "label": "Solutions",
    "file": "src/app/solutions/page.tsx"
  },
  {
    "id": "/solutions/platform-engineering",
    "label": "Platform Engineering",
    "file": "src/app/solutions/platform-engineering/page.tsx"
  },
  {
    "id": "/solutions/progressive-delivery",
    "label": "Progressive Delivery",
    "file": "src/app/solutions/progressive-delivery/page.tsx"
  },
  {
    "id": "/solutions/release-coordination",
    "label": "Release Coordination",
    "file": "src/app/solutions/release-coordination/page.tsx"
  },
  {
    "id": "/solutions/risk-intelligence",
    "label": "Risk Intelligence",
    "file": "src/app/solutions/risk-intelligence/page.tsx"
  },
  {
    "id": "/status",
    "label": "Status",
    "file": "src/app/status/page.tsx"
  },
  {
    "id": "/terms",
    "label": "Terms",
    "file": "src/app/terms/page.tsx"
  }
]

export const generatedLinks: GraphLink[] = [
  {
    "source": "/a-p-i",
    "target": "/cli",
    "kind": "link"
  },
  {
    "source": "/c-l-i",
    "target": "/api-reference",
    "kind": "link"
  },
  {
    "source": "/docs",
    "target": "/cli",
    "kind": "link"
  },
  {
    "source": "/docs",
    "target": "/api-reference",
    "kind": "link"
  },
  {
    "source": "/how-it-works",
    "target": "/docs",
    "kind": "link"
  },
  {
    "source": "/integrations",
    "target": "/api-reference",
    "kind": "link"
  },
  {
    "source": "/not-found",
    "target": "/docs",
    "kind": "link"
  },
  {
    "source": "/security",
    "target": "/pricing",
    "kind": "link"
  },
  {
    "source": "/for/-for-c-t-o",
    "target": "/how-it-works",
    "kind": "link"
  },
  {
    "source": "/for/-for-c-t-o",
    "target": "/security",
    "kind": "link"
  },
  {
    "source": "/for/-for-dev-ops",
    "target": "/solutions/progressive-delivery",
    "kind": "link"
  },
  {
    "source": "/for/-for-s-r-e",
    "target": "/solutions/instant-rollback",
    "kind": "link"
  },
  {
    "source": "/integrations/-integration-detail",
    "target": "/docs",
    "kind": "link"
  },
  {
    "source": "/products/-titan-foresight",
    "target": "/pricing",
    "kind": "link"
  },
  {
    "source": "/products/-titan-insight",
    "target": "/pricing",
    "kind": "link"
  },
  {
    "source": "/products/-titan-ledger",
    "target": "/pricing",
    "kind": "link"
  },
  {
    "source": "/products/-titan-ledger",
    "target": "/how-it-works",
    "kind": "link"
  },
  {
    "source": "/products/-titan-phoenix",
    "target": "/pricing",
    "kind": "link"
  },
  {
    "source": "/products/-titan-rollout",
    "target": "/solutions/release-coordination",
    "kind": "link"
  },
  {
    "source": "/products/-titan-sandbox",
    "target": "/pricing",
    "kind": "link"
  },
  {
    "source": "/products/-titan-shield",
    "target": "/pricing",
    "kind": "link"
  },
  {
    "source": "/products/-titan-shield",
    "target": "/solutions/release-coordination",
    "kind": "link"
  },
  {
    "source": "__nav__",
    "target": "/blog",
    "kind": "nav"
  },
  {
    "source": "__nav__",
    "target": "/pricing",
    "kind": "nav"
  },
  {
    "source": "__nav__",
    "target": "/journey",
    "kind": "nav"
  },
  {
    "source": "__nav__",
    "target": "/solutions",
    "kind": "nav"
  },
  {
    "source": "__nav__",
    "target": "/pricing",
    "kind": "nav"
  },
  {
    "source": "__nav__",
    "target": "/solutions",
    "kind": "nav"
  },
  {
    "source": "__nav__",
    "target": "/pricing",
    "kind": "nav"
  }
]
